name: 03 - Workflow Runners

on:
  push:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: "This job is running on an Ubuntu runner."


jobs:
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: "This job is running on an Windows runner."

jobs:
  mac0s-echo:
     runs-on: mac-latest
     steps:
      - name: Show OS
        run: "This job is running on an macOS runner."