name: Cache Node and NPM Dependencies
description: This action allows caching of both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir:
    required: false
    description: Working directory for the application
    default: .

runs:
  using: composite
  steps:
    - name: Setup Node version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache Dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{inputs.target-env}}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: ${{inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit-dependency'}}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
