name: 03 - Workflow Runners

on:
  push:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: "This job is running on a ${{ runner.os }} runner."
  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        shell: bash
        run: "This job is running on a ${{ runner.os }} runner."

  mac0s-echo:
    runs-on: mac-latest
    steps:
      - name: Show OS
        shell: bash
        run: "This job is running on a ${{ runner.os }} runner."
