# YOU SHOULD REALLY REVISE THIS YAML OUTPUT
name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      status:
        description: "Build Status"
        default: "success"
        type: choice
        options:
          - success
          - failure
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.step-build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"

      - name: Build
        id: step-build
        run: echo "status=${{inputs.status}}" >> "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying..."
