name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: false
        description: "Whether to execute cache step."

      node-version:
        description: "Node version to use."
        type: choice
        options:
          - 18.x,
          - 20.x,
          - 21.x
        default: 18.x

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{inputs.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build

      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
