name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS
on:
  workflow_dispatch:

jobs:
  run-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/js-dependency-update
