name: 17 - 2 - Custom Actions - Docker
run-name: 17 - 2 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - "https://www.github.com/"
          - "https://www.google.com/"
          - "http://www.invalid.com/"
        default: "https://www.google.com/"
      max_trials:
        default: "10"
        description: Maximum trials until action fails
        required: false

      delay:
        description: Delay in seconds between trials
        default: "5"
        required: false
jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_trials: ${{ inputs.max_trials  }}
          delay: ${{ inputs.delay }}
