name: 18 - 1 - Reusable Workflows - Reusable Definition
on:
  workflow_call:
    inputs:
      target-directory:
        type: string
        required: true
    outputs:
      build-status:
        description: The status of the build process
        value: ${{jobs.deploy.outputs.build-status}}
      url:
        description: The url of the deployed version
        value: ${{jobs.deploy.outputs.url}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      url: ${{steps.deploy.outputs.url}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        id: build
        run: |
          echo "Building using directory: ${{ inputs.target-directory }}"
          echo "status = success" >> $GITHUB_OUTPUT
      - name: deploy
        id: deploy
        run: |
          echo "Deploying to production"
          echo "url= https://example.com" >> $GITHUB_OUTPUT
